
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  # forward the public admin site
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # forward the public website
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  # forward the API
  config.vm.network "forwarded_port", guest: 8089, host: 8089
  # forward the Solr admin site
  config.vm.network "forwarded_port", guest: 8090, host: 8090
  # forward NginX
  #config.vm.network "forwarded_port", guest: 80, host: 8000
  #config.vm.network "forwarded_port", guest: 443, host: 8443

  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "./setup", "/home/ubuntu/setup"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 4
    # Example custom settings: v.customize ["modifyvm", :id, "--vram", "<vramsize in MB>"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo ''
    echo ' Run'
    echo '    vagrant ssh'
    echo ' and then run'
    echo '    bash setup/final-installation-steps.sh'
    echo ' To complete the installation.'
    echo ''
    echo ''
  SHELL
end
